---
title: T-Rekt's Blog
timezone: Asia/Bangkok
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
header-img: img/home-bg.jpg
email: vietthao2000@facebook.com
copyright_name: T-Rekt/J2TeaM
description: Security & IT Tutorial
baseurl: 
url: https://t-rekttt.github.io/
github_username: t-rekttt
facebook_username: vietthao2000
email_username: vietthao2000@facebook.com
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude:
- less
- node_modules
- Gruntfile.js
- package.json
- README.md
gems:
- jekyll-paginate
- jekyll-feed
